spring:
  ssl:
    bundle:
      jks:
        keycloak-client:
          keystore:
            location: ${SERVER_SSL_KEY_STORE}
            password: ${SSL_PASSWORD}
            type: PKCS12
          truststore:
            location: ${SERVER_SSL_TRUST_STORE}
            password: ${SSL_PASSWORD}
            type: PKCS12

server:
  port: 8443
  ssl:
    enabled: true
    client-auth: need
    key-store-type: PKCS12
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SSL_PASSWORD}
    trust-store-type: PKCS12
    trust-store: ${SERVER_SSL_TRUST_STORE}
    trust-store-password: ${SSL_PASSWORD}
